version: "3.7"

services:

  reverseproxy:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  web:
    depends_on:
      - reverseproxy
    build:
      context: ./Succubus.Web
    expose:
      - "5000"
    restart: always
